---
title: "Psicologia dell'Olfatto e del Gusto"
subtitle: "Corso sull'olfatto, i sapori, la percezione multisensoriale, e il comportamento umano in relazione ai sensi chimici"
author: "<a href='https://enricotoffalini.github.io/' target='blank'>Enrico Toffalini</a>"
format:
  html:
    theme: cosmo
    toc: false
    css: custom.css
---

Questo breve corso introduce gli studenti alla psicologia dell’olfatto e della percezione multisensoriale dei sapori. Partendo dall’importanza dell’olfatto nella vita quotidiana, vengono illustrate le basi anatomiche e fisiologiche dei sensi chimici, i principali disturbi olfattivi, e il legame tra olfatto e comportamento sociale. Il corso esplora inoltre le interazioni tra olfatto, gusto, vista e udito, fino ad applicazioni pratiche come la psicologia del vino, il marketing olfattivo e le differenze individuali e culturali nella percezione sensoriale.

## Slide del corso

* [1. Importanza dell'olfatto](1.%20SLIDE%20-%20Importanza%20olfatto.pdf){target="_blank"}
* [2. Cenni anatomici sui sensi chimici](2.%20SLIDE%20-%20Cenni%20anatomici%20sui%20sensi%20chimici.pdf){target="_blank"}
* [3. Disturbi dell'olfatto e conseguenze](3.%20SLIDE%20-%20Disturbi%20olfatto%20e%20conseguenze.pdf){target="_blank"}
* [4. Olfatto e comportamento sociale](4.%20SLIDE%20-%20Olfatto%20e%20comportamento%20sociale.pdf){target="_blank"}
* [5. Illusioni olfattive](5.%20SLIDE%20-%20Illusioni%20olfattive.pdf){target="_blank"}
* [6. Percezione multisensoriale dei sapori](6.%20SLIDE%20-%20Percezione%20multisensoriale%20dei%20sapori.pdf){target="_blank"}
* [7. Influenze uditive su sapori e comportamenti](7.%20SLIDE%20-%20Influenze%20uditive%20sui%20sapori%20e%20comportamenti.pdf){target="_blank"}
* [8. Psicologia del vino](8.%20SLIDE%20-%20Psicologia%20del%20vino.pdf){target="_blank"}
* [9. Olfatto e marketing](9.%20SLIDE%20-%20Olfatto%20e%20marketing.pdf){target="_blank"}
* [10. Differenze individuali e culturali](10.%20SLIDE%20-%20Differenze%20individuali%20e%20culturali.pdf){target="_blank"}

Sei un/a docente e vuoi le slide in power point? <a href="https://drive.google.com/file/d/1JUtLu4sst6cdUzywsuMp2neZfheyBZRN/view?usp=drive_link">Scarica lo zip!</a>

